### ISSUE TITLE
Tracker list suggestion

### ISSUE THREAD

**Issue by LexterS999** [m0zgen/bld-agregator#1]
Hi, guys. Check this out https://github.com/hagezi/dns-blocklists. It's a good adblocker list for your project. Below 1% false detections.

**Comment by m0zgen** [comment]
Thank you for your suggestion’s, you can check another one block list aggregator which have more daily updated additional domain lists:
* https://github.com/m0zgen/cactusd

Of course I'll get through your suggestion and also will try to add it to [OpenBLD.net](https://openbld.net) DNS service ;)
